name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi there @{{ github.event.issue.user.login }}! This is your first issue."
        pr-message: "🎉 Congrats ${{ github.event.pull_request.user.login}} for your first PR to this repo!"
